server:
  port: 8082

spring:
  application:
    name: boot-social-user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    propagation:
      type: w3c,b3
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{traceId:-}/%X{spanId:-}] [${spring.application.name}] %logger{36} - %msg%n"

