# db.url=jdbc:mysql://localhost:3306/learn_java?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
# db.user=java
# db.password=java123456

db.url=jdbc:mysql://localhost:3306/learn_java?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
db.user=admin
db.password=AdminPass_123!